import os
import concurrent.futures
from openai import OpenAI

openai_api_key = "EMPTY"
openai_api_base = os.getenv("JUDGE_URL")
model_name = "qwen"
_judge_client = None


def get_judge_client():
    global _judge_client
    if _judge_client is None:
        _judge_client = OpenAI(
            api_key=openai_api_key,
            base_url=openai_api_base,
        )
    return _judge_client

PROMPT_EVALUATOR_1 = """You are a Reasoning and Logical Consistency Evaluator. Your task is to objectively evaluate the reasoning quality and the logical coherence of the thought process of a multimodal deep research agent when executing tasks.
【Input Information】
- User Question (Question): {question}
- Execution Trajectory (Trajectory): {trajectory}
- Agent Final Output (Final Output): {final_output}
【Evaluation Criteria】
1. Reasoning Quality: Are the agent's analysis, planning, and deduction processes in the trajectory reasonable? Is there a clear logical progression between steps?
2. Evidence-based Deduction: Can the final conclusion be logically deduced from the clues collected in the trajectory? Are there forced conclusions or logical leaps?
3. Logical Consistency: Are there contradictory statements between the agent's thought process and the final output, or within the final output itself?
【Output Requirements】
Please evaluate based on the above criteria and output the results in the following format:
- Score: (Provide a comprehensive score from 1-10)
- Reason: (Explain the reason for the score, focusing on the quality of the reasoning chain and logical coherence, no more than 50 words.)"""



PROMPT_EVALUATOR_2 = """You are an Information Sourcing and Credibility Evaluator. Your task is to objectively evaluate whether the multimodal deep research agent correctly understood the retrieved information and whether there are any LLM hallucinations.
【Input Information】
- User Question (Question): {question}
- Execution Trajectory (Trajectory): {trajectory}
- Agent Final Output (Final Output): {final_output}
【Evaluation Criteria】
1. Information Understanding: Did the agent correctly understand the content retrieved in the trajectory? Is there any misinterpretation, misreading, or misattribution of the original text?
2. Faithfulness and Hallucination: Can all facts, data, and details in the final output find clear basis in the retrieval results of the trajectory? Is there any fabrication or hallucination?
【Output Requirements】
Please evaluate based on the above criteria and output the results in the following format:
- Score: (Provide a comprehensive score from 1-10)
- Reason: (Explain the reason for the score, focusing on the accuracy of understanding the retrieved content and information fidelity, no more than 50 words.)"""



PROMPT_EVALUATOR_3 = """You are a Result Validity Evaluator. Your task is to objectively evaluate the completeness of the multimodal deep research agent's final response and the actual completion status of the task.
【Input Information】
- User Question (Question): {question}
- Agent Final Output (Final Output): {final_output}
【Evaluation Criteria】
1. Response Status: Did the agent successfully generate a substantive final answer? Are there situations where it gave up halfway, did not attempt to answer, or only replied with "cannot find the answer/error occurred"?
【Output Requirements】
Please evaluate based on the above criteria and output the results in the following format:
- Score: (Provide a comprehensive score from 1-10)
- Reason: (Explain the reason for the score, focusing on the completeness of the final response and whether it answered effectively, no more than 50 words.)"""



PROMPT_FINAL_ARBITER = """You are the Final Arbiter. In the absence of a ground-truth answer, your one and only task is to determine whether the final answer generated by the multimodal deep research agent is correct.
The feedback from the three evaluators is provided for your reference. You need make a definitive judgment based on the factual evidence in the trajectory and the logical soundness of the final output.
【Input Information】
- User Question (Question): {question}
- Execution Trajectory (Trajectory): {trajectory}
- Agent Final Output (Final Output): {final_output}
- Evaluator 1 Feedback (Reasoning and Logical Consistency, Importance Weight: 0.5): 
{evaluator_1_result}
- Evaluator 2 Feedback (Information Sourcing and Credibility, Importance Weight: 0.3): 
{evaluator_2_result}
- Evaluator 3 Feedback (Result Validity, Importance Weight: 0.2): 
{evaluator_3_result}
【Adjudication Criteria】
A "Correct" answer must simultaneously meet the following conditions based on your own assessment:
1. Effective Response: The agent provided a substantive answer that directly addresses the user's question.
2. Faithful to Facts: The information in the final output is entirely supported by the retrieved content in the trajectory.
3. Logical Consistency: The deduction from the trajectory evidence to the final conclusion is logically sound and free of contradictions.
【Output Requirements】
You must output ONLY a single letter representing your final verdict. Do not include any explanations, markdown formatting, punctuation, or extra text.
- Output "A" if the answer is Correct.
- Output "B" if the answer is Incorrect."""




def run_evaluator(evaluator_prompt_template: str, question: str, final_output: str, trajectory = "") -> str:
    if trajectory:
        prompt = evaluator_prompt_template.format(
            question=question,
            trajectory=trajectory,
            final_output=final_output
        )
    else:
        prompt = evaluator_prompt_template.format(
            question=question,
            final_output=final_output
        )
    return call_llm(prompt, temperature=0.1)

def call_llm(prompt_text: str, temperature: float = 0.2) -> str:
    try:
        response = get_judge_client().chat.completions.create(
            model=model_name,
            messages=[{"role": "user", "content": prompt_text}],
            temperature=temperature,
            max_tokens=1000,
            extra_body={"chat_template_kwargs": {"enable_thinking": False}}
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"LLM Call Error: {e}")
        return "Error"

def evaluate_agent_without_gt(question: str, trajectory: str, final_output: str) -> dict:
    eval_1_result = run_evaluator(
        PROMPT_EVALUATOR_1, 
        question=question, trajectory=trajectory, final_output=final_output
    )
    eval_2_result = run_evaluator(
        PROMPT_EVALUATOR_2, 
        question=question, trajectory=trajectory, final_output=final_output
    )
    eval_3_result = run_evaluator(
        PROMPT_EVALUATOR_3, 
        question=question, final_output=final_output
    )
    ac_prompt = PROMPT_FINAL_ARBITER.format(
        question=question,
        trajectory=trajectory,
        final_output=final_output,
        evaluator_1_result=eval_1_result,
        evaluator_2_result=eval_2_result,
        evaluator_3_result=eval_3_result
    )
    ac_result = call_llm(ac_prompt, temperature=0.0)
    final_verdict_char = ac_result.replace(".", "").replace(" ", "").strip().upper()
    is_correct = "correct" if "A" in final_verdict_char else "incorrect"
    return {
        "is_correct": is_correct,
        "raw_verdict": final_verdict_char,
        "evaluator_1_feedback": eval_1_result,
        "evaluator_2_feedback": eval_2_result,
        "evaluator_3_feedback": eval_3_result
    }

