hydra:
  searchpath:
    - /path/to/APEx/Writer-Train/Train/verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 4096
  max_response_length: 2048
  train_batch_size: 64
  return_raw_chat: True
  return_multi_modal_inputs: False
  custom_cls:
    path: "/path/to/APEx/Writer-Train/Train/writer_skill/writer_dataset.py"
    name: WriterRLHFDataset

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang
    multi_turn:
      enable: False

custom_reward_function:
  path: "/path/to/APEx/Writer-Train/Train/writer_skill/writer_dataset.py"
  name: compute_score
