SKILL_OUTPUT_SCHEMA = """{
  "operation": "synthesize | refine | create | skip",
  "skill": {
    "skill_name": "<category>_<modality>_strategy",
    "category": "<category>",
    "modality": "<modality>",
    "description": "One-sentence description of the skill",
    "procedure": [
      {"step": 1, "action": "Concrete action description", "purpose": "Why this step matters"}
    ],
    "pitfalls": ["Common mistake to avoid"],
    "win_rate": 0.0,
    "version": 1,
    "evidence_count": 0
  },
  "absorbed_ids": ["list of memory data_ids whose patterns are now captured in the skill"]
}"""


SYSTEM_PROMPT = (
    "You are a skill synthesis and evolution expert in a memory-augmented agent system. "
    "Your job is to analyze batches of task execution memories and distill them into "
    "reusable, structured skill documents. Skills encode proven strategies and common "
    "pitfalls for specific task categories. Output valid JSON only."
)


SKILL_SYNTHESIS_PROMPT = """Analyze the following batch of task memories from the "{category}" category ({modality} modality) and synthesize a reusable skill document.

[Memories]
{formatted_memories}

Requirements:
1. Identify common strategies in successful (correct) memories — what search patterns, reasoning steps, or tool usage led to correct answers.
2. Identify common failure modes in incorrect memories — what mistakes, wrong assumptions, or missing steps caused failures.
3. Synthesize a structured skill with clear, atomic procedure steps that generalize across these memories.
4. List specific pitfalls to avoid, grounded in observed failure cases.
5. Compute win_rate as the ratio of correct memories to total memories.
6. Set operation to "synthesize", version to 1, evidence_count to the number of memories.

Output a JSON object with this exact structure (no extra text before or after the JSON):
{skill_output_schema}"""


SKILL_EVOLUTION_PROMPT = """Given the current skill and a batch of new evidence memories, decide how to update the skill.

[Current Skill]
{current_skill}

[New Evidence Memories]
{formatted_memories}

Choose ONE operation:
- "refine": Failures expose a specific defect in the current procedure. Fix the defective steps and update pitfalls, but preserve steps validated by successes (conservative editing — do not break what works).
- "create": Memories reveal an effective strategy pattern NOT covered by the current skill. Create a new skill.
- "skip": New evidence is insufficient to justify changes. Keep the skill unchanged, only update win_rate and evidence_count.

Conservative editing principles:
- Successful memories define invariants — the procedure steps they validate must NOT be modified.
- Failed memories define modification targets — only change steps related to the failure cause.
- Never remove a pitfall that is still relevant.

Output a JSON object with this exact structure (no extra text before or after the JSON):
{skill_output_schema}"""


SKILL_JUDGE_PROMPT = """You are an expert evaluator for skill documents generated by a memory-augmented agent system.

Your job is to assess the quality of a generated skill by comparing it against the source memories and (if present) the existing skill.

[Source Memories]
{memories}

[Existing Skill (null if this is a new synthesis)]
{current_skill}

[Generated Skill]
{generated_skill}

Evaluate the generated skill on these dimensions:
1. Procedure quality: Are the steps concrete, actionable, and in a logical order? Each step should specify a single operation (e.g., invoke a tool, verify a fact, cross-check results). Vague steps like "analyze the data" without specifying how are a weakness.
2. Pitfall grounding: Are the pitfalls derived from actual failure cases in the memories? Generic warnings not tied to observed failures are low value.
3. Pattern coverage: Does the skill accurately capture the successful strategies from the memories? Are key success patterns missing?
4. Win rate consistency: Is the reported win_rate roughly consistent with the ratio of correct to total memories?

Grade the generated skill as one of:
A: HIGH_QUALITY — procedure is clear and executable, pitfalls are grounded in real failures from the memories, description is accurate, the skill can be directly used by a downstream planner.
B: ACCEPTABLE — basic structure is complete but has notable weaknesses: steps are vague, pitfalls are generic, weak connection to the source memories, or missing important patterns.
C: LOW_QUALITY — procedure is not executable or has critical gaps, skill does not reflect the memories, or contains contradictions.

Just return the letter "A", "B", or "C", with no other text.
"""


def format_memories(memories: list[dict]) -> str:
    lines = []
    for i, mem in enumerate(memories, 1):
        status_tag = f"[{mem.get('status', 'new').upper()}]"
        judgement_tag = f"[{mem['judgement'].upper()}]"
        lines.append(
            f"Memory {i} {status_tag} {judgement_tag}:\n"
            f"  Question: {mem['question']}\n"
            f"  Workflow: {mem['workflow_summary']}"
        )
    return "\n\n".join(lines)


def build_writer_prompt(category: str, modality: str, current_skill: str, memories: list[dict]) -> list[dict]:
    formatted_memories = format_memories(memories)

    if current_skill is None or current_skill == "null" or current_skill.strip() == "":
        user_content = SKILL_SYNTHESIS_PROMPT.format(
            category=category,
            modality=modality,
            formatted_memories=formatted_memories,
            skill_output_schema=SKILL_OUTPUT_SCHEMA,
        )
    else:
        user_content = SKILL_EVOLUTION_PROMPT.format(
            current_skill=current_skill,
            formatted_memories=formatted_memories,
            skill_output_schema=SKILL_OUTPUT_SCHEMA,
        )

    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]
